# Use root/example as user/password credentials
version: "3.1"

services:
  server:
    image: hafezfhmi/meow-gallery-server
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    ports:
      - 3001:3001
    env_file:
      - ./server/.env
    environment:
      CHOKIDAR_USEPOLLING: true
    volumes:
      - ./server:/usr/src/app

  db:
    image: mysql:8.0.30
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3307:3306
    secrets:
      - db_root_password
      - db_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: example
      MYSQL_USER: admin
      MYSQL_PASSWORD_FILE: /run/secrets/db_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:7.0
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt

volumes:
  mysql:
  redis:
