# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql:8.0.30
    restart: always
    volumes: 
      - mysql:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: example
      MYSQL_USER: admin
      MYSQL_PASSWORD_FILE: /run/secrets/db_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt

volumes:
  mysql: