const dotenv = require("dotenv");

dotenv.config();
const {
  GMAIL_EMAIL,
  GMAIL_SECRETS,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  DB_NAME,
  DB_USERNAME,
  DB_PASSWORD,
  DB_HOST,
  DB_PORT,
  DB_DIALECT,
  REDIS_HOST,
  REDIS_PORT,
  PORT,
} = process.env;

module.exports = {
  GMAIL_EMAIL,
  GMAIL_SECRETS,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  DB_NAME,
  DB_USERNAME,
  DB_PASSWORD,
  DB_HOST,
  DB_PORT,
  DB_DIALECT,
  REDIS_HOST,
  REDIS_PORT,
  PORT,
};
